// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TogglerApi.Context;

namespace TogglerApi.Migrations
{
    [DbContext(typeof(ToggleContext))]
    partial class ToggleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TogglerApi.Models.Toggle.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("TogglerApi.Models.Toggle.Toggle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasAlternateKey("Key");

                    b.ToTable("Toggles");
                });

            modelBuilder.Entity("TogglerApi.Models.Toggle.ToggleState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<long>("ServiceId");

                    b.Property<long>("ToggleId");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<bool>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ToggleId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("TogglerApi.Models.Toggle.ToggleState", b =>
                {
                    b.HasOne("TogglerApi.Models.Toggle.Service", "Service")
                        .WithMany("States")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TogglerApi.Models.Toggle.Toggle", "Toggle")
                        .WithMany("States")
                        .HasForeignKey("ToggleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
